package com.snap.valdi.hello_world.test

import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.assertion.ViewAssertions.matches
import androidx.test.espresso.matcher.ViewMatchers.isDisplayed
import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.snap.valdi.hello_world.StartActivity
import com.snap.valdi.test.ValdiElementAssertions
import com.snap.valdi.test.ValdiElementMatchers
import com.snap.valdi.test.ValdiEspresso
import com.snap.valdi.test.ValdiViewMatchers
import org.hamcrest.Matchers.startsWith
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Drives the real HelloWorld app screen (the `StartActivity` generated by
 * `valdi_application`) with the Valdi Espresso bindings.
 *
 * This is the end-to-end path an app developer takes: launch the app, wait for the Valdi
 * component tree to render, then locate elements by their Valdi attributes rather than by
 * Android view ids.
 */
@RunWith(AndroidJUnit4::class)
class HelloWorldAppTest {

    @get:Rule
    val activityRule = ActivityScenarioRule(StartActivity::class.java)

    @Test
    fun inflatesAValdiRootView() {
        onView(ValdiViewMatchers.withValdiRootView()).check(matches(isDisplayed()))
    }

    @Test
    fun rendersWelcomeLabel() {
        // The label reads "Welcome to <APP_NAME>!", where APP_NAME comes from the app's
        // native module (MyNativeModuleFactory), so match on the prefix only.
        ValdiEspresso.waitUntil(ValdiElementMatchers.withText(startsWith(WELCOME_PREFIX)))

        ValdiEspresso.onValdiElement(ValdiElementMatchers.withText(startsWith(WELCOME_PREFIX)))
            .check(ValdiElementAssertions.matches(ValdiElementMatchers.isDisplayed()))
    }

    @Test
    fun rendersWelcomeLabelInsideScrollElement() {
        ValdiEspresso.waitUntil(ValdiElementMatchers.withText(startsWith(WELCOME_PREFIX)))

        ValdiEspresso.onValdiElement(ValdiElementMatchers.isScroll())
            .check(
                ValdiElementAssertions.matches(
                    ValdiElementMatchers.hasDescendant(
                        ValdiElementMatchers.withText(startsWith(WELCOME_PREFIX))
                    )
                )
            )
    }

    private companion object {
        const val WELCOME_PREFIX = "Welcome to "
    }
}
