//
//  GeneratedTypesDiagnostics.swift
//  Compiler
//
//  Created by saniul on 17/07/2019.
//

import Foundation

func nativeApiDeclaredVersion(annotations: [ValdiTypeScriptAnnotation]) -> String? {
    return annotations.first(where: { $0.name == ValdiAnnotationType.version.rawValue })?.positionalPayload
}

func nativeApiEffectiveMemberVersion(declared: String?, container: String?) -> String? {
    guard let declared else {
        return container
    }
    guard let container else {
        return declared
    }
    if declared == "__PLACEHOLDER__" || container == "__PLACEHOLDER__" {
        return "__PLACEHOLDER__"
    }
    guard let declaredVersion = Int(declared) else {
        return declared
    }
    guard let containerVersion = Int(container) else {
        return container
    }
    return String(max(declaredVersion, containerVersion))
}

//////////
// This file defines set of easily-encodable structs describing the classes,
// interfaces, enums etc. generated by the compiler.
// These are then used to emit diagnostics JSON files
//////////

struct GeneratedTypesSummary: Encodable {
    let sourceFilePath: String
    let generatedTypes: [GeneratedTypeDescription]

    func toFile() -> File {
        let data = (try? toJSON(outputFormatting: [.prettyPrinted, .sortedKeys])) ?? Data()
        let file = File.data(data)
        return file
    }
}

enum GeneratedTypeDescription: Encodable {
    case `class`(GeneratedNativeClassDescription)
    case interface(GeneratedNativeInterfaceDescription)
    case `enum`(GeneratedEnumDescription)
    case function(GeneratedFunctionDescription)
    case module(GeneratedNativeInterfaceDescription)
    case viewClass(GeneratedViewClassDescription)

    enum CodingKeys: CodingKey {
        case `class`
        case interface
        case `enum`
        case function
        case module
        case viewClass
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case let .class(value):
            try container.encode(value, forKey: .class)
        case let .interface(value):
            try container.encode(value, forKey: .interface)
        case let .enum(value):
            try container.encode(value, forKey: .enum)
        case let .function(value):
            try container.encode(value, forKey: .function)
        case let .module(value):
            try container.encode(value, forKey: .module)
        case let .viewClass(value):
            try container.encode(value, forKey: .viewClass)
        }
    }

    func typeName(for platform: Platform) -> String? {
        switch platform {
        case .ios:
            return iosTypeName
        case .android:
            return androidTypeName
        case .web:
            return webTypeName
        case .cpp:
            return cppTypeName
        }
    }

    var iosTypeName: String? {
        switch self {
        case let .class(this):
            return this.iosTypeName
        case let .interface(this):
            return this.iosTypeName
        case let .enum(this):
            return this.iosTypeName
        case let .function(this):
            return this.containingIosTypeName
        case let .module(this):
            return this.iosTypeName
        case let .viewClass(this):
            return this.iosTypeName
        }
    }

    var androidTypeName: String? {
        switch self {
        case let .class(this):
            return this.androidTypeName
        case let .interface(this):
            return this.androidTypeName
        case let .enum(this):
            return this.androidTypeName
        case let .function(this):
            return this.containingAndroidTypeName
        case let .module(this):
            return this.androidTypeName
        case let .viewClass(this):
            return this.androidClassName
        }
    }

    var cppTypeName: String? {
        switch self {
        case let .class(this):
            return this.cppTypeName
        case let .interface(this):
            return this.cppTypeName
        case let .enum(this):
            return this.cppTypeName
        case let .function(this):
            return this.containingCppTypeName
        case let .module(this):
            return this.cppTypeName
        case .viewClass:
            return nil
        }
    }

    var webTypeName: String? {
        // TODO: Implement this
        return nil
    }

    var valueToSortBy: String {
        switch self {
        case let .class(this):
            return this.iosTypeName ?? this.androidTypeName ?? ""
        case let .interface(this):
            return this.iosTypeName ?? this.androidTypeName ?? ""
        case let .enum(this):
            return this.iosTypeName ?? this.androidTypeName ?? ""
        case let .function(this):
            return this.functionName
        case let .module(this):
            return this.iosTypeName ?? this.androidTypeName ?? ""
        case let .viewClass(this):
            return this.iosTypeName ?? this.androidClassName ?? ""
        }
    }

    var isNativeApi: Bool {
        switch self {
        case let .class(description),
             let .interface(description),
             let .module(description):
            return description.isNativeApi
        case .enum, .function:
            return true
        case .viewClass:
            return false
        }
    }

    /// False for reference bindings to a pre-existing native type (@NativeClass/@NativeInterface
    /// with `isGenerated: false`). Everything else describes a type the compiler generates.
    var isGenerated: Bool {
        switch self {
        case let .class(description),
             let .interface(description),
             let .module(description):
            return description.isGenerated
        case .enum, .function, .viewClass:
            return true
        }
    }
}

struct GeneratedNativeClassDescription: Encodable {
    let iosTypeName: String?
    let androidTypeName: String?
    let cppTypeName: String?
    let properties: [PropertyDescription]
    let declaredVersion: String?
    let effectiveVersion: String?
    let isNativeApi: Bool
    // False for @NativeClass/@NativeInterface reference bindings to a pre-existing native type.
    // These don't generate the type, so several TS modules may legitimately reference the same one;
    // the collision verifier must skip them (not encoded — metadata output is unaffected).
    let isGenerated: Bool

    enum CodingKeys: CodingKey {
        case iosTypeName
        case androidTypeName
        case cppTypeName
        case properties
        case declaredVersion
        case effectiveVersion
    }

    init(model: ValdiModel, baseline: String?) {
        iosTypeName = model.iosType?.name
        androidTypeName = model.androidClassName
        cppTypeName = model.cppType?.declaration.fullTypeName
        declaredVersion = model.declaredVersion
        isNativeApi = model.isNativeApi
        isGenerated = true
        let effectiveVersion = model.declaredVersion ?? (model.isNativeApi ? baseline : nil)
        self.effectiveVersion = effectiveVersion
        properties = model.properties.map { property in
            if model.isNativeApi {
                return PropertyDescription(
                    prop: property,
                    declaredVersion: property.declaredVersion,
                    containerVersion: effectiveVersion
                )
            } else {
                return PropertyDescription(prop: property)
            }
        }
    }

    init(nativeClass: TypeScriptNativeClass,
         annotations: [ValdiTypeScriptAnnotation],
         baseline: String?) {
        iosTypeName = nativeClass.iosType?.name
        androidTypeName = nativeClass.androidClass
        cppTypeName = nativeClass.cppType?.declaration.fullTypeName
        properties = []
        declaredVersion = nativeApiDeclaredVersion(annotations: annotations)
        effectiveVersion = declaredVersion ?? baseline
        isNativeApi = true
        isGenerated = nativeClass.isGenerated
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iosTypeName, forKey: .iosTypeName)
        try container.encodeIfPresent(androidTypeName, forKey: .androidTypeName)
        try container.encodeIfPresent(cppTypeName, forKey: .cppTypeName)
        try container.encode(properties, forKey: .properties)
        try container.encode(declaredVersion, forKey: .declaredVersion)
        try container.encode(effectiveVersion, forKey: .effectiveVersion)
    }
}

typealias GeneratedNativeInterfaceDescription = GeneratedNativeClassDescription

struct GeneratedEnumCaseDescription<T: Encodable>: Encodable {
    let name: String
    let value: T
    let declaredVersion: String?
    let effectiveVersion: String?

    enum CodingKeys: CodingKey {
        case name
        case value
        case declaredVersion
        case effectiveVersion
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
        try container.encode(declaredVersion, forKey: .declaredVersion)
        try container.encode(effectiveVersion, forKey: .effectiveVersion)
    }
}

struct GeneratedEnumDescription: Encodable {
    let iosTypeName: String?
    let androidTypeName: String?
    let cppTypeName: String?

    let intCases: [GeneratedEnumCaseDescription<Int>]?
    let stringCases: [GeneratedEnumCaseDescription<String>]?
    let declaredVersion: String?
    let effectiveVersion: String?

    enum CodingKeys: CodingKey {
        case iosTypeName
        case androidTypeName
        case cppTypeName
        case intCases
        case stringCases
        case declaredVersion
        case effectiveVersion
    }

    static func from(exportedEnum: ExportedEnum, baseline: String?) -> GeneratedEnumDescription {
        let declaredVersion = exportedEnum.declaredVersion
        let effectiveVersion = declaredVersion ?? baseline

        let intCases: [GeneratedEnumCaseDescription<Int>]?
        let stringCases: [GeneratedEnumCaseDescription<String>]?
        switch exportedEnum.cases {
        case let .enum(cases):
            intCases = cases.map { enumCase in
                return GeneratedEnumCaseDescription(
                    name: enumCase.name,
                    value: enumCase.value,
                    declaredVersion: enumCase.declaredVersion,
                    effectiveVersion: nativeApiEffectiveMemberVersion(
                        declared: enumCase.declaredVersion,
                        container: effectiveVersion
                    )
                )
            }
            stringCases = nil
        case let .stringEnum(cases):
            intCases = nil
            stringCases = cases.map { enumCase in
                return GeneratedEnumCaseDescription(
                    name: enumCase.name,
                    value: enumCase.value,
                    declaredVersion: enumCase.declaredVersion,
                    effectiveVersion: nativeApiEffectiveMemberVersion(
                        declared: enumCase.declaredVersion,
                        container: effectiveVersion
                    )
                )
            }
        }

        return GeneratedEnumDescription(
            iosTypeName: exportedEnum.iosType?.name,
            androidTypeName: exportedEnum.androidTypeName,
            cppTypeName: exportedEnum.cppType?.declaration.fullTypeName,
            intCases: intCases,
            stringCases: stringCases,
            declaredVersion: declaredVersion,
            effectiveVersion: effectiveVersion
        )
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iosTypeName, forKey: .iosTypeName)
        try container.encodeIfPresent(androidTypeName, forKey: .androidTypeName)
        try container.encodeIfPresent(cppTypeName, forKey: .cppTypeName)
        try container.encodeIfPresent(intCases, forKey: .intCases)
        try container.encodeIfPresent(stringCases, forKey: .stringCases)
        try container.encode(declaredVersion, forKey: .declaredVersion)
        try container.encode(effectiveVersion, forKey: .effectiveVersion)
    }
}

struct GeneratedFunctionDescription: Encodable {
    let containingIosTypeName: String?
    let containingAndroidTypeName: String?
    let containingCppTypeName: String?
    let functionName: String
    let parameters: [PropertyDescription]
    let returnType: PropertyTypeDescription
    let declaredVersion: String?
    let effectiveVersion: String?

    enum CodingKeys: CodingKey {
        case containingIosTypeName
        case containingAndroidTypeName
        case containingCppTypeName
        case functionName
        case parameters
        case returnType
        case declaredVersion
        case effectiveVersion
    }

    static func from(exportedFunction: ExportedFunction, baseline: String?) -> GeneratedFunctionDescription {
        let declaredVersion = exportedFunction.declaredVersion
        return GeneratedFunctionDescription(
            containingIosTypeName: exportedFunction.containingIosType?.name,
            containingAndroidTypeName: exportedFunction.containingAndroidTypeName,
            containingCppTypeName: exportedFunction.containingCppType?.declaration.fullTypeName,
            functionName: exportedFunction.functionName,
            parameters: exportedFunction.parameters.map(PropertyDescription.init),
            returnType: PropertyTypeDescription(propType: exportedFunction.returnType),
            declaredVersion: declaredVersion,
            effectiveVersion: declaredVersion ?? baseline
        )
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(containingIosTypeName, forKey: .containingIosTypeName)
        try container.encodeIfPresent(containingAndroidTypeName, forKey: .containingAndroidTypeName)
        try container.encodeIfPresent(containingCppTypeName, forKey: .containingCppTypeName)
        try container.encode(functionName, forKey: .functionName)
        try container.encode(parameters, forKey: .parameters)
        try container.encode(returnType, forKey: .returnType)
        try container.encode(declaredVersion, forKey: .declaredVersion)
        try container.encode(effectiveVersion, forKey: .effectiveVersion)
    }
}

struct GeneratedViewClassDescription: Encodable {
    let iosTypeName: String?
    let androidClassName: String?

    let iosViewModelClassName: String?
    let androidViewModelClassName: String?

    let iosComponentContextClassName: String?
    let androidComponentContextClassName: String?

    var accessors: [AccessorDescription]?
    var nativeActions: [String]?
    var emitActions: [String]?

    struct AccessorDescription: Encodable {
        let iosTypeName: String?
        let androidClassName: String?
        let name: String
    }
}

// class for indirection
class PropertyTypeDescription: Encodable {
    let typeStr: String

    private(set) var functionTypeMetadata: FunctionTypeMetadata?
    struct FunctionTypeMetadata: Encodable {
        let parameters: [PropertyDescription]
        let returnType: PropertyTypeDescription
    }

    private(set) var genericTypeMetadata: GenericTypeMetadata?
    struct GenericTypeMetadata: Encodable {
        let types: [PropertyTypeDescription]
    }

    private(set) var customTypeMetadata: CustomTypeMetadata?
    struct CustomTypeMetadata: Encodable {
        let iosTypeName: String?
        let androidClassName: String?
        let cppTypeName: String?
    }

    private(set) var typeParameterMetadata: TypeParameterMetadata?
    struct TypeParameterMetadata: Encodable {
        let typeParameterName: String
    }

    init(propType: ValdiModelPropertyType) {
        switch propType {
        case .string:
            typeStr = "string"
        case .double:
            typeStr = "double"
        case .bool:
            typeStr = "bool"
        case .long:
            typeStr = "long"
        case let .array(elementType):
            typeStr = "array"
            let description = PropertyTypeDescription(propType: elementType)
            genericTypeMetadata = GenericTypeMetadata(types: [description])
        case .bytes:
            typeStr = "bytes"
        case let .map(keyType, valueType):
            typeStr = "map"
            genericTypeMetadata = GenericTypeMetadata(types: [
                PropertyTypeDescription(propType: keyType),
                PropertyTypeDescription(propType: valueType),
            ])
        case .any:
            typeStr = "any"
        case .void:
            typeStr = "void"
        case let .function(parameters, returnType, _, _, _):
            typeStr = "function"
            let parameters = parameters.map(PropertyDescription.init)
            let returnType = PropertyTypeDescription(propType: returnType)
            functionTypeMetadata = FunctionTypeMetadata(parameters: parameters,
                                                        returnType: returnType)
        case let .object(nodeClassMapping):
            typeStr = "object"
            customTypeMetadata = CustomTypeMetadata(nodeClassMapping: nodeClassMapping)
        case let .genericTypeParameter(name):
            typeStr = "genericTypeParameter"
            typeParameterMetadata = .init(typeParameterName: name)
        case let .genericObject(nodeClassMapping, typeArguments):
            typeStr = "genericObject"
            customTypeMetadata = CustomTypeMetadata(nodeClassMapping: nodeClassMapping)
            genericTypeMetadata = GenericTypeMetadata(types: typeArguments.map(PropertyTypeDescription.init))
        case let .enum(nodeClassMapping):
            typeStr = "enum"
            customTypeMetadata = CustomTypeMetadata(nodeClassMapping: nodeClassMapping)
        case .promise(let typeArgument):
            typeStr = "promise"
            genericTypeMetadata = GenericTypeMetadata(types: [PropertyTypeDescription(propType: typeArgument)])
        case let .nullable(innerType):
            typeStr = "nullable"
            genericTypeMetadata = GenericTypeMetadata(types: [PropertyTypeDescription(propType: innerType)])
        }
    }

}

private extension PropertyTypeDescription.CustomTypeMetadata {
    init(nodeClassMapping: ValdiNodeClassMapping) {
        iosTypeName = nodeClassMapping.iosType?.name
        androidClassName = nodeClassMapping.androidClassName
        cppTypeName = nodeClassMapping.cppType?.declaration.fullTypeName
    }
}

struct PropertyDescription: Encodable {
    let name: String
    let isOptional: Bool

    let type: PropertyTypeDescription
    let declaredVersion: String?
    let effectiveVersion: String?
    private let emitsVersionMetadata: Bool

    // not for interfaces
    let omitConstructor: OmitConstructorParams?

    enum CodingKeys: CodingKey {
        case name
        case isOptional
        case type
        case declaredVersion
        case effectiveVersion
        case omitConstructor
    }

    init(prop: ValdiModelProperty) {
        name = prop.name
        isOptional = prop.type.isOptional
        type = PropertyTypeDescription(propType: prop.type.unwrappingOptional)
        omitConstructor = prop.omitConstructor
        declaredVersion = nil
        effectiveVersion = nil
        emitsVersionMetadata = false
    }

    init(prop: ValdiModelProperty, declaredVersion: String?, containerVersion: String?) {
        name = prop.name
        isOptional = prop.type.isOptional
        type = PropertyTypeDescription(propType: prop.type.unwrappingOptional)
        omitConstructor = prop.omitConstructor
        self.declaredVersion = declaredVersion
        effectiveVersion = nativeApiEffectiveMemberVersion(
            declared: declaredVersion,
            container: containerVersion
        )
        emitsVersionMetadata = true
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(isOptional, forKey: .isOptional)
        try container.encode(type, forKey: .type)
        if emitsVersionMetadata {
            try container.encode(declaredVersion, forKey: .declaredVersion)
            try container.encode(effectiveVersion, forKey: .effectiveVersion)
        }
        try container.encodeIfPresent(omitConstructor, forKey: .omitConstructor)
    }
}
