/**
 * Valdi web playground HMR dev server wrapper.
 *
 * Bazel materializes sources into bazel-out snapshots, so webpack-dev-server
 * running from runfiles watches frozen copies — workspace edits never reach
 * HMR. This wrapper bridges the gap by symlinking the Bazel-managed
 * node_modules into the workspace playground dir, then starting
 * webpack-dev-server from the workspace. Webpack watches real source files;
 * HMR triggers on every edit.
 *
 * Triggered via `bzl run //<playground>:dev` — `BUILD_WORKSPACE_DIRECTORY`
 * (set by `bzl run`) hands over the path to the user's workspace. The
 * `:dev` target generated by the `valdi_web_playground` macro passes
 * `--package-path` (the playground's bazel package) and `--config` (the
 * webpack config path relative to that package) as args.
 */

'use strict';

const path = require('path');
const fs = require('fs');

function parseArgs(argv) {
  const opts = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--package-path') opts.packagePath = argv[++i];
    else if (a === '--config') opts.config = argv[++i];
  }
  return opts;
}

const { packagePath, config: configPath } = parseArgs(process.argv.slice(2));

if (!packagePath) {
  console.error('hmr-server: --package-path is required (set by the valdi_web_playground macro).');
  process.exit(1);
}

const wsRoot = process.env.BUILD_WORKSPACE_DIRECTORY;
if (!wsRoot) {
  console.error('BUILD_WORKSPACE_DIRECTORY not set. Run via `bzl run :dev`, not as a standalone binary.');
  process.exit(1);
}

const runfilesPlaygroundDir = process.cwd();
const webpack = require(path.join(runfilesPlaygroundDir, 'node_modules/webpack'));
const WebpackDevServer = require(path.join(runfilesPlaygroundDir, 'node_modules/webpack-dev-server'));

const workspacePlaygroundDir = path.join(wsRoot, packagePath);
if (!fs.existsSync(workspacePlaygroundDir)) {
  console.error(`Workspace playground dir not found: ${workspacePlaygroundDir}`);
  process.exit(1);
}

const resolvedConfigPath = configPath || 'playground/webpack.hmr.config.js';

function bridgeSymlink(target, linkPath) {
  if (fs.existsSync(linkPath) || fs.lstatSync(linkPath, { throwIfNoEntry: false })) {
    const stat = fs.lstatSync(linkPath);
    if (stat.isSymbolicLink()) {
      const current = fs.readlinkSync(linkPath);
      if (current === target) return;
      fs.unlinkSync(linkPath);
    } else {
      console.error(
        `Refusing to clobber non-symlink at ${linkPath}. ` +
        `Remove it manually and re-run :dev (it will be recreated as a symlink to ${target}).`,
      );
      process.exit(1);
    }
  }
  fs.symlinkSync(target, linkPath, 'dir');
  console.log(`Symlinked ${linkPath} -> ${target}`);
}

bridgeSymlink(
  path.join(runfilesPlaygroundDir, 'node_modules'),
  path.join(workspacePlaygroundDir, 'node_modules'),
);

process.chdir(workspacePlaygroundDir);

const config = require(path.join(workspacePlaygroundDir, resolvedConfigPath));
const compiler = webpack(config);
const server = new WebpackDevServer(config.devServer, compiler);

server.start().then(() => {
  const port = config.devServer && config.devServer.port;
  console.log(`HMR dev server listening on http://localhost:${port}`);
  console.log(`Watching workspace: ${workspacePlaygroundDir}`);
}).catch(err => {
  console.error('Failed to start HMR dev server:', err);
  process.exit(1);
});
