# Deps every Valdi module target depends on.

# `android_mvn` is generated by Valdi's maven module extension and is only
# use_repo'd into Valdi's own MODULE.bazel, so it is absent from an external
# consumer's repo mapping. A plain "@android_mvn//..." string resolves against
# the consumer package that calls valdi_module and fails as an unknown repo;
# Label() resolves the apparent name against this .bzl's repo (@valdi) instead,
# so the injected deps stay internal to Valdi. (Label() is a no-op under
# WORKSPACE, where apparent names map to themselves.)
COMMON_ANDROIDX_DEPS = [
    Label("@android_mvn//:androidx_annotation_annotation"),
    Label("@android_mvn//:androidx_appcompat_appcompat"),
    Label("@android_mvn//:androidx_core_core"),
    Label("@android_mvn//:javax_inject_javax_inject"),
]

COMMON_FRAMEWORK_DEPS = [
    "@valdi//valdi_core:valdi_core_java",
    "@valdi//valdi:valdi_java",
]
