"""Repository rule that downloads a single Swift toolchain archive and
registers a rules_swift-compatible toolchain pointing at it.

Motivation: rules_swift's Linux autoconfig computes `toolchain_root`
from `repository_ctx.which("swiftc").dirname.dirname` at repo-fetch
time and bakes the result as a literal string into the generated
`swift_toolchain(root=...)`. If the host's `swiftc` is a swiftly shim,
the resolved root lands on `~/.local/share/swiftly` rather than the
real toolchain dir, and every `swift_binary` link fails looking for
`swiftrt.o` under `{root}/lib/swift/linux/{arch}/`.

This rule sidesteps that: it downloads a pinned Swift archive, knows
its absolute on-disk path via `repository_ctx.path(...)`, and emits a
`swift_toolchain(root=<abs_path>)` plus a `toolchain(...)` registration
against `@build_bazel_rules_swift//toolchains:toolchain_type`. Combined
with a `register_toolchains(...)` in the root module's MODULE.bazel
that precedes rules_swift's autoconfig registration, this toolchain
wins resolution on Linux.

macOS uses rules_swift's autoconfigured xcode-toolchain (xcrun isn't
shimmed, so the autoconfig works there).
"""

_BUILD_FILE_TEMPLATE = """\
# Auto-generated by remote_swift_toolchain_repository.bzl.
load("@build_bazel_rules_swift//swift/toolchains:swift_toolchain.bzl", "swift_toolchain")

package(default_visibility = ["//visibility:public"])

exports_files(["{swift_relative_path}", "swift_version"])

swift_toolchain(
    name = "rules_swift_hermetic_toolchain",
    arch = "{arch}",
    features = [{features}],
    os = "linux",
{parsed_version_attr}    root = "{root}",
    version_file = ":swift_version",
)

toolchain(
    name = "rules_swift_toolchain",
    exec_compatible_with = [{exec_compatible_with}],
    target_compatible_with = [{exec_compatible_with}],
    toolchain = ":rules_swift_hermetic_toolchain",
    toolchain_type = "@build_bazel_rules_swift//toolchains:toolchain_type",
)

# rules_swift 3.1.2 only adds -L for lib/swift/<os> (dynamic libs).
# The static archives (libicu*swift.a, libFoundation.a, etc.) live under
# lib/swift_static/<os>/ and need an explicit search path.
cc_library(
    name = "swift_static_search_path",
    linkopts = ["-L{root}/lib/swift_static/linux"],
)
"""

# Linux + Swift 5.10.x: features statically known. Mirrors what
# _create_linux_toolchain in
# @build_bazel_rules_swift//swift/internal:swift_autoconfiguration.bzl
# appends. Hardcoded because the repo rule may evaluate on a macOS
# host, where executing a Linux swiftc to probe would fail.
#
# lld_gc_workaround is ENABLED: without `-Wl,-z,nostart-stop-gc`
# (which rules_swift's linking glue adds only when this feature is
# on), lld's --gc-sections drops the __start_swift5_* / __stop_swift5_*
# encapsulation symbols that swiftrt.o's image constructor references,
# and every swift_binary link on Linux fails. Enabled unconditionally
# because the Swift releases we vend ship an lld that supports the flag.
#
# static_stdlib is ENABLED: rules_swift consults this feature on the
# *toolchain* target (not the binary) to source the Swift runtime from
# `lib/swift_static/linux` (.a archives) instead of `lib/swift/linux`
# (.so files). Linux binaries we ship (e.g. the Valdi compiler) must
# not depend on a Swift runtime being installed on the host. The Valdi
# compiler is built via //compiler/compiler:local_valdi_compiler (see
# src/open_source/compiler/compiler/BUILD.bazel).
_LINUX_SWIFT_FEATURES = [
    "swift.module_map_no_private_headers",
    "swift.use_autolink_extract",
    "swift.use_module_wrap",
    "swift._supports_upcoming_features",
    "-swift._supports_v6",
    "swift.lld_gc_workaround",
    "swift.static_stdlib",
]

_ARCH_TO_CPU_CONSTRAINT = {
    "x86_64": "@platforms//cpu:x86_64",
    "aarch64": "@platforms//cpu:arm64",
}

def _remote_swift_toolchain_repository_impl(ctx):
    ctx.download_and_extract(
        url = ctx.attr.url,
        sha256 = ctx.attr.sha256,
        stripPrefix = ctx.attr.strip_prefix,
    )

    # swift_toolchain.root must be an absolute path -- rules_swift bakes
    # it into -L and -Wl,-rpath flags on the link command line. Match
    # what the upstream autoconfig does: two dirnames up from swiftc
    # resolves to the toolchain's "usr" dir, which has lib/swift/... below.
    swift_path = ctx.path(ctx.attr.swift_relative_path)
    root_abs = str(swift_path.dirname.dirname)

    # Placeholder version_file. rules_swift treats it as a tool input
    # for cache invalidation; content just has to exist and change
    # when the toolchain does. strip_prefix is unique per version.
    ctx.file("swift_version", ctx.attr.strip_prefix or "unknown", executable = False)

    cpu_constraint = _ARCH_TO_CPU_CONSTRAINT.get(ctx.attr.arch)
    if cpu_constraint == None:
        fail("Unsupported arch '{}'; extend _ARCH_TO_CPU_CONSTRAINT.".format(ctx.attr.arch))

    exec_compatible_with = ", ".join([
        "\"@platforms//os:linux\"",
        "\"{}\"".format(cpu_constraint),
    ])

    features_str = ", ".join([
        "\"{}\"".format(f)
        for f in _LINUX_SWIFT_FEATURES
    ])

    # rules_swift 4.x made `parsed_version` a mandatory attr on swift_toolchain;
    # 3.x has no such attr and rejects it outright. This repo is generated once
    # per root module and the roots may resolve different rules_swift major
    # versions, so probe the rule for the attr rather than committing to either
    # shape. Capability check, not a version comparison, so it needs no
    # follow-up when the remaining roots move to 4.x.
    swift_toolchain_bzl = Label("@build_bazel_rules_swift//swift/toolchains:swift_toolchain.bzl")
    if "\"parsed_version\"" in ctx.read(swift_toolchain_bzl):
        parsed_version_attr = "    parsed_version = \"{}\",\n".format(ctx.attr.version)
    else:
        parsed_version_attr = ""

    ctx.file(
        "BUILD.bazel",
        _BUILD_FILE_TEMPLATE.format(
            swift_relative_path = ctx.attr.swift_relative_path,
            arch = ctx.attr.arch,
            root = root_abs,
            features = features_str,
            exec_compatible_with = exec_compatible_with,
            parsed_version_attr = parsed_version_attr,
        ),
        executable = False,
    )

remote_swift_toolchain_repository = repository_rule(
    implementation = _remote_swift_toolchain_repository_impl,
    attrs = {
        "url": attr.string(
            mandatory = True,
            doc = "HTTP URL of the Swift toolchain archive.",
        ),
        "sha256": attr.string(
            doc = "SHA-256 of the archive. Strongly recommended.",
        ),
        "strip_prefix": attr.string(
            doc = "Top-level directory inside the archive to strip.",
        ),
        "version": attr.string(
            mandatory = True,
            doc = "Swift release version, e.g. '5.10.1'. Emitted as rules_swift 4.x's parsed_version; ignored on 3.x.",
        ),
        "arch": attr.string(
            mandatory = True,
            doc = "Architecture string consumed by rules_swift's swift_toolchain (e.g. 'x86_64', 'aarch64').",
        ),
        "swift_relative_path": attr.string(
            default = "usr/bin/swift",
            doc = "Path to the swift binary inside the (post-strip) archive.",
        ),
    },
    doc = "Downloads a Swift toolchain and registers it against @build_bazel_rules_swift//toolchains:toolchain_type.",
)
