packages:
 - .
 - ../../../compiler/companion
 - ../../../compiler/companion/remotedebug-ios-webkit-adapter
 - ../../../src/valdi_modules/src/valdi/valdi_protobuf
 - ../../../tools/valdi_web_devtools
 - ../../../experiments/helloworld_playground
