#!/usr/bin/env python3
"""
Extract pure type definitions (interfaces and enums) from test/proto.d.ts
for web-compatible usage without native dependencies.
"""

import re

def extract_pure_types(input_file):
    with open(input_file, 'r') as f:
        lines = f.readlines()
    
    output = []
    skip_until_depth = None  # When set, skip until we return to this depth
    depth = 0
    in_namespace = False
    
    for line in lines:
        stripped = line.strip()
        
        # Skip imports with 'from'
        if stripped.startswith('import ') and ' from ' in line:
            continue
        
        # Skip "Generated by" comments
        if 'Generated by' in line or 'DO NOT EDIT!' in line:
            continue
        
        # Track brace depth
        depth += line.count('{') - line.count('}')
        
        # If we're skipping (inside a class), check if we've exited
        if skip_until_depth is not None:
            if depth <= skip_until_depth:
                skip_until_depth = None
            continue
        
        # Check if this is a class declaration - start skipping
        if re.search(r'\bexport class \w+', line):
            skip_until_depth = depth - 1  # Skip until we exit this class
            continue
        
        # Keep namespaces, interfaces, and enums
        if (re.search(r'\bexport (namespace|interface|const enum) \w+', line) or
            stripped.startswith('export namespace ')):
            output.append(line)
            continue
        
        # If we're at top level or in a namespace/interface/enum, keep the line
        # This includes field definitions, comments, closing braces, etc.
        if skip_until_depth is None:
            # Skip empty lines at the start
            if not output and not stripped:
                continue
            output.append(line)
    
    return ''.join(output)

if __name__ == '__main__':
    input_file = '../../test/proto.d.ts'
    output = extract_pure_types(input_file)
    
    # Check if Long type is used
    needs_long_import = 'Long' in output or ': Long' in output
    
    # Add header
    header = """/**
 * Web-compatible type definitions extracted from test/proto.d.ts
 * 
 * This file contains ONLY pure type definitions (interfaces and enums).
 * All class declarations and native dependencies have been removed.
 * 
 * Generated by extract_types.py - DO NOT EDIT MANUALLY
 * To regenerate: cd web/test && python3 extract_types.py > proto-types.d.ts
 */

"""
    
    # Add Long import if needed
    if needs_long_import:
        header += "import Long from 'long';\n\n"
    
    print(header + output)
