#!/usr/bin/env bash
#
# validate_external_config.sh — Verify that the open-source repo configuration
# remains valid after Copybara transforms are applied.
#
# This script simulates the key Copybara transforms (see copy.bara.sky) and
# validates the resulting configuration would work on the public GitHub CI.
# It runs inside the internal monorepo so regressions are caught BEFORE
# Copybara mirrors the change.
#
# Called by: client_validate_valdi_open_source.sh (SnapCI)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPEN_SOURCE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

FAILURES=0
fail() {
    echo "FAIL: $1"
    FAILURES=$((FAILURES + 1))
}
pass() { echo "PASS: $1"; }

echo "=== Validating External Build Configuration ==="

# ---------------------------------------------------------------------------
# 1. NPM lockfile compatibility
#
# The publish-npm.yml workflow upgrades to npm@latest (v11+) which requires
# lockfileVersion >= 3. Lockfiles generated by npm <= 8 use v2 and fail
# with "Missing: @esbuild/... from lock file" under npm 11's stricter
# lockfile parsing.
# ---------------------------------------------------------------------------
echo ""
echo "--- NPM lockfile compatibility ---"

for lockfile in "$OPEN_SOURCE_DIR"/npm_modules/*/package-lock.json; do
    pkg_name="$(basename "$(dirname "$lockfile")")"
    version=$(grep -m1 '"lockfileVersion"' "$lockfile" | grep -Eo '[0-9]+')
    if [[ "$version" -lt 3 ]]; then
        fail "$pkg_name/package-lock.json has lockfileVersion $version (need >= 3 for npm 11+)"
    else
        pass "$pkg_name/package-lock.json lockfileVersion $version"
    fi
done

# ---------------------------------------------------------------------------
# 2. Copybara transform markers
#
# The internal↔open-source build flags both live in bzl/valdi/config.bzl, which
# Copybara swaps for its config.bzl.copybara twin as a whole file (no longer via
# core.replace on scattered markers). Verify the internal values are still present
# so a rename/retype is caught before the mirror silently ships the wrong config.
# ---------------------------------------------------------------------------
echo ""
echo "--- Copybara transform markers ---"

if grep -q 'use_local_compiler_default = False' "$OPEN_SOURCE_DIR/bzl/valdi/config.bzl"; then
    pass "use_local_compiler_default marker present (internal=False, copybara twin flips to True)"
else
    fail "use_local_compiler_default marker missing or malformed in bzl/valdi/config.bzl — copybara .copybara swap will ship the wrong flag value"
fi

if grep -q 'INTERNAL_BUILD = True' "$OPEN_SOURCE_DIR/bzl/valdi/config.bzl"; then
    pass "INTERNAL_BUILD marker present (internal=True, copybara twin flips to False)"
else
    fail "INTERNAL_BUILD marker missing or malformed in bzl/valdi/config.bzl — copybara .copybara swap will ship the wrong flag value"
fi

# The .copybara twin is what actually ships to public github.com (copy.bara.sky
# swaps it over config.bzl), so validate it carries the flipped external values.
# A twin left with the internal values would silently mirror the wrong config.
CONFIG_TWIN="$OPEN_SOURCE_DIR/bzl/valdi/config.bzl.copybara"
if [[ ! -f "$CONFIG_TWIN" ]]; then
    fail "config.bzl.copybara missing — copybara will have nothing to swap over the external config.bzl"
elif ! grep -q 'INTERNAL_BUILD = False' "$CONFIG_TWIN"; then
    fail "config.bzl.copybara has wrong INTERNAL_BUILD (expected False for the external build) — public repo would ship internal tooling flags"
elif ! grep -q 'use_local_compiler_default = True' "$CONFIG_TWIN"; then
    fail "config.bzl.copybara has wrong use_local_compiler_default (expected True for the external build) — public repo would expect prebuilt tooling it doesn't have"
else
    pass "config.bzl.copybara carries the external values (INTERNAL_BUILD=False, use_local_compiler_default=True)"
fi

if [[ -f "$OPEN_SOURCE_DIR/bzl/additional_dependencies.bzl.copybara" ]]; then
    pass "additional_dependencies.bzl.copybara exists"
else
    fail "additional_dependencies.bzl.copybara missing — copybara will fail to overwrite external bzl/additional_dependencies.bzl"
fi

# ---------------------------------------------------------------------------
# 3. use_local_compiler=true build graph validity
#
# On the public repo, Copybara sets use_local_compiler=True. Verify that the
# build graph is valid under that flag on the current platform. This catches
# issues like missing Swift toolchains on Linux before they reach the public CI.
# ---------------------------------------------------------------------------
echo ""
echo "--- Build graph validity with use_local_compiler=true ---"

pushd "$OPEN_SOURCE_DIR" > /dev/null

# Pure C++ targets should always be analyzable, even with use_local_compiler=true.
# If this fails, it means the valdi_toolchain registration is broken (e.g., Swift
# toolchain missing on Linux).
CPP_TARGETS="//valdi:test_snap_drawing //valdi:test_hermes"
if bzl cquery "set($CPP_TARGETS)" --//bzl/valdi:use_local_compiler=true --output=label 2>/dev/null; then
    pass "C++ test targets analyzable with use_local_compiler=true"
else
    fail "C++ test targets CANNOT be analyzed with use_local_compiler=true — the registered valdi_toolchain likely can't resolve (missing Swift toolchain on Linux?)"
fi

# The compiler itself should be analyzable. On macOS this means rules_swift
# finds Xcode; on Linux it means the Swift toolchain is properly configured.
if bzl cquery //compiler/compiler:local_valdi_compiler --//bzl/valdi:use_local_compiler=true --output=label 2>/dev/null; then
    pass "local_valdi_compiler target analyzable"
else
    fail "local_valdi_compiler target CANNOT be analyzed — Swift toolchain likely missing"
fi

# Targets that use valdi_module() need the compiler. Verify the full chain works.
if bzl cquery //valdi:test_layout --//bzl/valdi:use_local_compiler=true --output=label 2>/dev/null; then
    pass "test_layout (uses compiler) analyzable with use_local_compiler=true"
else
    fail "test_layout CANNOT be analyzed with use_local_compiler=true — compiler toolchain chain is broken"
fi

popd > /dev/null

# ---------------------------------------------------------------------------
# 4. No stale git-lfs references
#
# After the LFS removal, no files should reference git-lfs (except the
# mirroring scripts which are excluded from the public repo).
# ---------------------------------------------------------------------------
echo ""
echo "--- No stale git-lfs references ---"

# Search for git-lfs references excluding mirroring scripts and this test
LFS_HITS=$(grep -rn "git.lfs\|git-lfs\|lfs: true\|setupGitLfs\|checkGitLfsInit" \
    "$OPEN_SOURCE_DIR" \
    --include="*.sh" --include="*.ts" --include="*.yml" --include="*.yaml" --include="*.md" \
    --exclude-dir=mirroring \
    --exclude="validate_external_config.sh" \
    2>/dev/null || true)

if [[ -z "$LFS_HITS" ]]; then
    pass "No stale git-lfs references"
else
    fail "Stale git-lfs references found:"
    echo "$LFS_HITS"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== External config validation complete ==="
if [[ "$FAILURES" -gt 0 ]]; then
    echo "RESULT: $FAILURES check(s) failed"
    exit 1
else
    echo "RESULT: All checks passed"
fi
